name: fastbot_humble

services:
  fastbot-humble-container:
    image: theconstructai/fastbot:humble
    pull_policy: always
    privileged: true
    network_mode: host
    container_name: fastbot-humble-container
    volumes:
      - /var/lib/theconstruct.rrl/cyclonedds.xml:/var/lib/theconstruct.rrl/cyclonedds.xml
      - /dev:/dev
      - ./ros_entrypoint.sh:/ros_entrypoint.sh
      - ./bringup.launch.xml:/root/ros2_ws/install/fastbot_bringup/share/fastbot_bringup/launch/bringup.launch.xml       
    environment:
      - RMW_IMPLEMENTAION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds.xml
    entrypoint: /ros_entrypoint.sh
    command: ["ros2", "launch", "fastbot_bringup", "bringup.launch.xml", "robot_name:=fastbot_1"]
    restart: always
