name: fastbot_humble

services:
  fastbot-humble-container:
    image: theconstructai/fastbot:humble
    pull_policy: always
    privileged: true
    network_mode: host
    container_name: fastbot-humble
    volumes:
      - /var/lib/theconstruct.rrl/cyclonedds.xml:/var/lib/theconstruct.rrl/cyclonedds.xml
      - /dev:/dev
      - ./volumes/ros_entrypoint.sh:/ros_entrypoint.sh
      - ./volumes/bringup.launch.xml:/root/ros2_ws/install/fastbot_bringup/share/fastbot_bringup/launch/bringup.launch.xml   
      - ./volumes/rplidar.launch.py:/root/ros2_ws/install/rplidar_ros/share/rplidar_ros/launch/rplidar.launch.py    
      - ./volumes/laser_scan_matcher.launch.py:/root/ros2_ws/install/ros2_laser_scan_matcher/share/ros2_laser_scan_matcher/launch/laser_scan_matcher.launch.py
    environment:
      - RMW_IMPLEMENTAION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds.xml
    entrypoint: /ros_entrypoint.sh
    command: ["ros2", "launch", "fastbot_bringup", "bringup.launch.xml", "robot_name:=fastbot_1"]
    restart: always
